//done
/*
 * Repeating Sub-Sequence
Asked in:  
Google
Given a string A, find if there is any subsequence that repeats itself.

A subsequence of a string is defined as a sequence of characters generated by deleting some characters in the string without changing the order of the remaining characters.

NOTE : sub-sequence length should be greater than or equal to 2.



Input Format:

The first and the only argument of input contains a string A.
Output Format:

Return an integer, 0 or 1:
    => 0 : False
    => 1 : True
Constraints:

1 <= length(A) <= 100
Examples:

Input 1:
    A = "abab"

Output 1:
    1

Explanation 1:
    "ab" is repeated.

Input 2:
    A = "abba"
    
Output 2:
    0

Explanation 2:
    There is no repeating subsequence.
 */

package interviewbit;

public class Repeating_Sub_Sequence {
	
	public int anytwo(String A) {
        int len=A.length();
        if(len<=2)
        return 0;
        
        String ans=LCS(A);
        if(ans.length()<2)
        return 0;
        return 1;
        
    }
	
    public String LCS(String s1){
        String ans="";
        int last_ind=1;
        for(int i=0;i<s1.length();i++)
        {
            char ch1=s1.charAt(i);
            int ind=s1.indexOf(ch1,last_ind);
            //System.out.print(ind+" ");
            if(ind!=-1 && ind!=i)
            {ans+=ch1;
            last_ind=ind;}
        }
        return ans;
    }
    
    

}
